### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by zcai0612** [tirer-lab/DDPG#1]
Thanks a lot for the brilliant work! May I ask the time of code release?

**Comment by ezacngm** [comment]
Hi Tomer and Tom,
Your work is so enlightening for me, while there is still some confusing stuff. I would be really happy if you could share the code implementation of the math. I hope I can learn from your great idea ASAP.

Thanks.

**Comment by TomerG711** [comment]
Hi @zcai0612 and @ezacngm , the code is uploaded. You can clone this repository and use it.
