### ISSUE TITLE
AttributeError: Can't pickle local object 'Diffusion.ddpg_wrapper.<locals>.seed_worker'

### ISSUE THREAD

**Issue by asdn321** [tirer-lab/DDPG#2]
F:\DDPG\venv\Scripts\python.exe F:/DDPG/main.py --config imagenet_256.yml --path_y imagenet --deg sr_bicubic --sigma_y 0.05 -i IDPG_imagenet_sr_bicubic_sigma_y_0.05 --inject_noise 0 --gamma 30 --eta_tilde 0.2 --step_size_mode 0 --deg_scale 4 --operator_imp SVD
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
F:\DDPG\venv\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
F:\DDPG\venv\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: F:\DDPG\venv\lib\site-packages\lpips\weights\v0.1\alex.pth
INFO - main.py - 2024-08-07 08:56:13,510 - Argument config: 'imagenet_256.yml'
INFO - main.py - 2024-08-07 08:56:13,510 - Argument deg: 'sr_bicubic'
INFO - main.py - 2024-08-07 08:56:13,510 - Argument deg_scale: 4.0
INFO - main.py - 2024-08-07 08:56:13,510 - Argument eta_tilde: 0.2
INFO - main.py - 2024-08-07 08:56:13,510 - Argument exp: 'exp'
INFO - main.py - 2024-08-07 08:56:13,510 - Argument gamma: 30.0
INFO - main.py - 2024-08-07 08:56:13,510 - Argument image_folder: 'exp\\image_samples\\IDPG_imagenet_sr_bicubic_sigma_y_0.05'
INFO - main.py - 2024-08-07 08:56:13,510 - Argument inject_noise: 0
INFO - main.py - 2024-08-07 08:56:13,510 - Argument ni: True
INFO - main.py - 2024-08-07 08:56:13,511 - Argument operator_imp: 'SVD'
INFO - main.py - 2024-08-07 08:56:13,511 - Argument path_y: 'imagenet'
INFO - main.py - 2024-08-07 08:56:13,511 - Argument save_observed_img: False
INFO - main.py - 2024-08-07 08:56:13,511 - Argument scale_ls: 1.0
INFO - main.py - 2024-08-07 08:56:13,511 - Argument seed: 1234
INFO - main.py - 2024-08-07 08:56:13,511 - Argument sigma_y: 0.05
INFO - main.py - 2024-08-07 08:56:13,511 - Argument step_size_mode: 0
INFO - main.py - 2024-08-07 08:56:13,511 - Argument subset_end: -1
INFO - main.py - 2024-08-07 08:56:13,511 - Argument subset_start: -1
INFO - main.py - 2024-08-07 08:56:13,511 - Argument verbose: 'info'
INFO - main.py - 2024-08-07 08:56:13,511 - Argument xi: 1e-05
INFO - main.py - 2024-08-07 08:56:13,511 - Argument zeta: 0.5
INFO - main.py - 2024-08-07 08:56:13,543 - Using device: cuda
Run IDPG. Operators implementation via SVD. 100 sampling steps. Task: sr_bicubic. Noise level: 0.05.
building dataset from exp\imagenet_val.txt
read meta done
Dataset has size 8
F:\DDPG\venv\lib\site-packages\torch\utils\data\dataloader.py:561: UserWarning: This DataLoader will create 32 worker processes in total. Our suggested max number of worker in current system is 4 (`cpuset` is not taken into account), which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Start from 0
  0%|          | 0/8 [00:00<?, ?it/s]
ERROR - main.py - 2024-08-07 08:56:20,517 - Traceback (most recent call last):
  File "F:/DDPG/main.py", line 185, in main
    runner.sample(logger)
  File "F:\DDPG\guided_diffusion\diffusion.py", line 217, in sample
    self.ddpg_wrapper(model, cls_fn, logger)
  File "F:\DDPG\guided_diffusion\diffusion.py", line 385, in ddpg_wrapper
    for x_orig, classes in pbar:
  File "F:\DDPG\venv\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "F:\DDPG\venv\lib\site-packages\torch\utils\data\dataloader.py", line 442, in __iter__
    return self._get_iterator()
  File "F:\DDPG\venv\lib\site-packages\torch\utils\data\dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "F:\DDPG\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1043, in __init__
    w.start()
  File "D:\Program Files\Python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\Program Files\Python38\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Program Files\Python38\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "D:\Program Files\Python38\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Program Files\Python38\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'Diffusion.ddpg_wrapper.<locals>.seed_worker'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Program Files\Python38\lib\multiprocessing\spawn.py", line 107, in spawn_main
    new_handle = reduction.duplicate(pipe_handle,
  File "D:\Program Files\Python38\lib\multiprocessing\reduction.py", line 79, in duplicate
    return _winapi.DuplicateHandle(
OSError: [WinError 6]

**Comment by TomerG711** [comment]
Hi, it looks like you run the code on Windows. The code was tested on Linux (Ubuntu) only. Please setup a VM or Docker and see if the error still occurs.
